[package]
name = "mysql_client"
version = "0.1.0"
authors = ["Robertas <robertasjasmontas@gmail.com>"]

[dependencies.mysql]
mysql = "*"
default-features = false
features = ["socket"]

[dependencies]
gtk = "0.0.4"
glib = "^0"

